### ISSUE TITLE
Missing env file: 

### ISSUE THREAD

**Issue by alnavarrop99** [markospy/personal_finance_management#1]
Tienes que proveer un anchivo . env para que corra el proyecto en otros equipos.
![image](https://github.com/user-attachments/assets/81e1f42f-7789-4a26-9454-0a3ea5be33a8)

Puedes crear para compartir 
- `.env.local`.
- `.env.development`
- `.env.example`

O puedes simplemente adjuntarlo en el **`README.md`** siempre que el proyecto sea de prueba.

**Comment by markospy** [comment]
Muchas gracias. Ya agregué el archivo `.env.development`.
