### ISSUE TITLE
Compose version

### ISSUE THREAD

**Issue by alnavarrop99** [markospy/personal_finance_management#2]
Adjunta al archivo de **`README.md`** una seccion donde incluyas las versiones de los builders, ts, engines (node o bun), docker y docker compose utilizada 

_Ejemplo_: 
**Warning**: `docker compose`
![image](https://github.com/user-attachments/assets/7a49bcce-b481-4d5f-9f88-72f083cb3bae)

**Comment by markospy** [comment]
Actualicé el **README.md**. Gracias por la observación.

> ### Versiones Utilizadas

> A continuación se detallan las versiones de las herramientas y tecnologías utilizadas en este proyecto:
> 
> Builders:
> 
> Vite: v5.4.1
> TypeScript: v5.5.3
> 
> Engines:
> 
> Node.js: v22.3.0
> Docker: v27.0.3
> 
> Docker Compose: v2.28.1-desktop.1
