### ISSUE TITLE
Use case @tanstack-query + ui handle

### ISSUE THREAD

**Issue by alnavarrop99** [markospy/personal_finance_management#3]
### Ejemplo de casos de uso de @tanstack-query en **`React`**

_Codigo Legacy_: 
```tsx
const API_URL = 'http://localhost:8000';
```
- No difnas las url en variables definelas en el archivo **`.env`**

_Difinicion_: 
```.env
API_URL = http://localhost:8000
```

_Implementacion_: 
```.env
axios.create({
	baseURL: proccess.env.API_URL,
	timeout: 1000,
	headers: {'Accept': 'application/json'},
})
```

---

_Codigo Legacy_: 
```tsx
export const getMonthlySumary = (token: string, date:  DateIn): Promise<MonthlySumary> => {
    return axi.get('/statistics/monthly-summary',
        {
            params: {
                year: date.year,
                month: date.month
            },
            headers: {'Authorization': `Bearer ${token}`}
        }
    ).then(
		response => {
			console.log(response.status)
			return response.data;
		}
	).catch(error => {
		// Manejo de errores
		if (error.response) {
			console.log('Error en la respuesta del servidor:', error.response.data);
			console.log('Estado del error:', error.response.status);
			console.log('Encabezados del error:', error.response.headers);
		} else if (error.request) {
			console.log('No se recibió respuesta:', error.request);
		} else {
			console.log('Error al configurar la solicitud:', error.message);
		}
		console.log('Configuración de la solicitud:', error.config);

		// Puedes lanzar el error de nuevo si quieres que la promesa se rechace
		return Promise.reject(error);
	});
}
```
- Piensa correctamente como quieres manipular los datos de la peticcion **`http`**
    1. realizas el fetch de datos.
    2. parseas el resultado una vez obtenida la promesa
    3. en caso de fallo devuelves el objeto error en forma de una promesa mediante `Promise.rejected`, pero **`error`** es un objeto no una excepcion.
 - Simplemente devuelve el resultado 

_Difinicion_: 
```tsx
export type Res = Record<string, any>

export type Error = {
    status: number,
    msg: string
}

export const fetchData = (token: string, date:  DateIn): Promise<Res | Error> => {
    const res: TRes | undefined = undefined
    try {
        const data = axi.get('/statistics/monthly-summary', {
            params: { year: date.year, month: date.month},
            headers: {'Authorization': `Bearer ${token}`}
        })
        res = data.data
    } catch(error){
       res = { status: errorr.response.status, msg: error.message }
    }
    return res
}
```
- En este punto sabes que aunque la peticion falle siempre tendras un resultado, ya sea de tipo **`Promise<Res>`** o de tipo **`Promise<Error>`**, nunca undefined, ni nunca esto lanzara una excpcion porque toda la logica se parsea para siempre retornar un objeto.
---
_Codigo Legacy_:
```tsx
export function GetTransactions(token: string) {
    return {
        querKey: ['transactions'],
        queryFn: () => getTransactions(token)
    }
}
```
- Recuerda siempre tener cuidado con esto te ofresco dos alternativas en funcion de la forma que yo defini mi funcion de fetch de datos, es decir sin parametros.

_Definicion_:
1. **_Tipos_**: 
```tsx
export const opt:  {
    querKey: ['example'],
    queryFn: fetchData
} satisfies Parameters<typeof nCliente.ensureQueryData>[0]
```

2. Helper de **`tanstock-query`** (mejor via):
```tsx
import { queryOption } from '@tanstack/react-query'
export const opt = queryOption ({
    querKey: ['example'],
    queryFn: fetchData
})
```
- el metodo ya presenta inferencia de tipos, pero solo funciona para los **`GET`** no para mutar con **`POST`**
---
_Codigo Legacy_: 
```tsx
import { useRouteError } from "react-router-dom";

export default function ErrorPage() {
  const error = useRouteError();
  console.error(error);

  return (
    <div className="flex flex-col items-center justify-center h-full">
      <h1>Oops!</h1>
      <p>Sorry, an unexpected error has occurred.</p>
      <p>
        <i>{error.statusText || error.message}</i>
      </p>
    </div>
  );
}
```
- Dejamos claro que el fetch de datos siempre devuelve un error, en vez de crear un componente para manejar un error encontrado de una excpcion crea uno que te devuelva los diferentes casos y envuelvelos en tus componentes y manejas el error local siempre y no glabal como intentas.

_Implementacion_: 
```tsx
import { type Error } from "~/some/fetchData"

export function FetchHandle( { children }: React.PropsWithChildren<{data: Res | Error}> ) {    
    if(data.status === 422){
        return <p>Ups :(, Error incoming ... ( reload page )</p>
    }

    return <>{children}</>
}

export function Example( { data }: {data: Res} ) {    
    return <div>
        <p>{data.username}</p>
        <p>{data.email}</p>
    </div>
}

export default function Layout( ) {    
    const data = useQuery(opt)
    return <FetchHandle data={data}>
        <Example data={data} />
    </FetchHandle>
}
```
---
No es la unica forma que existe, el uso en la libreria de **`useRouteError`** capta cuando una excepcion es lanzada y muestra ese error, y esta de por si tampoco es la unica, aqui te va en react-router-dom 2 vias para hacer componentes manejadores de errores,

_Definicion_: **API**.
```ts
import { queryOption } from '@tanstack/react-query'

export type Res = Record<string, any>

export type Error = {
    status: number,
    msg: string
}

export const fetchData = (token: string, date:  DateIn): Promise<Res | Error> => {
    const res: TRes | undefined = undefined
    try {
        const data = axi.get('/statistics/monthly-summary', {
            params: { year: date.year, month: date.month},
            headers: {'Authorization': `Bearer ${token}`}
        })
        res = data.data
    } catch(error){
       throw new Error( JSON.stringify({ status: errorr.response.status, msg: error.message }) )
      /* para que funcione el componente de react-router-dom de error handle es necesario lanzar una excpcion, y aqui era el porque fallaba tu codigo legacy*/
    }
    return res
}

export const opt = queryOption ({
    querKey: ['example'],
    queryFn: fetchData
})
```

_Definicion_: Error handler with hook. 
```tsx
// some/comp/error.tsx
export default function ErrorHandle( ) {    
    const error = useRouteError()
    return (<div>
        <p>Ups :(, Error incoming ... ( reload page )</p>
        <p>{error as string}</p>
    </div>)
}
```

_Definicion_: Error handler like a component. 
```tsx
// some/comp/error.tsx
export default function ErrorHandle( {error}: {error: string} ) {    
    const error = useRouteError()
    return (<div>
        <p>Ups :(, Error incoming ... ( reload page )</p>
        <p>{error}</p>
    </div>)
}
```

_Definicion_: **`react-router-dom`** -> route config . 
```tsx
// some/comp/error.tsx
export default function App( ) {    
    return ( 
        <RouterProvider router={[
            {path: '/', Component: Example, ErrorBoundary: ErrorHandle} // para ambos casos
            // {path: '/', Component: Example, errorElement: <ErrorHandle />} tambien puede ser asi, pero solo el primer caso
        ]} />
    )
}
```
---
Cuando usas **`@tanstock-query`** con **`react-router-dom`** estas usando mal el metodo: **`ensureQueryData`**, este se usa dentro de un **`loader`** de **`react-router-dom`** y ese metodo se encarga de asegurar si o si los datos en forma de **`JS`** no en un hook de react, se usa junto con **`useQuery`** donde con el primero carga los datos en el loader y una vez asegurados, es decir cacheados los recuperas con el hook 

_Definicion_: Correct use of **`.ensureQueryData`**. 
```tsx
import { nClient } from "~/some/client"
import { opt } from "~/some/fetchData"

export const loader = ( {  }: LoaderFunctionsArgs ) => {
    cons data = nClient.ensureQueryData(opt)
    return data
}
```

_Definicion_: Pagina
```tsx
import { opt } from "~/some/fetchData

export default function Example( ) {    
    const data = useQuery(opt)
    return (<div>
        <p>{data.username}</p>
        <p>{data.email}</p>
    </div>)
}
```

_Definicion_: **`react-router-dom`** -> route config . 
```tsx
// some/comp/error.tsx
export default function App( ) {    
    return ( 
        <RouterProvider router={createBrowserRouter([
            {path: '/', loader: loader, element: <Example />}
        ])} />
    )
}
```

**Comment by markospy** [comment]
Recomendación para cargar la variable de entorno:
`axios.create({
	baseURL: process.env.API_URL,
	timeout: 1000,
	headers: {'Accept': 'application/json'},
})`

En el caso de crear una app con vite el objeto process lanzara el siguiente error en la consola del navegador:
_Uncaught ReferenceError: process is not defined_

La manera correcta de hacerlo es mediante el objeto _import.meta_:

`import axios from "axios";

const url = import.meta.env.VITE_REACT_APP_API_BASE_URL 

if (!url) {
    throw new Error("La variable de entorno REACT_APP_API_URL no está definida");
}

export const axi = axios.create({
	baseURL: url,
	timeout: 1000,
	headers: {'Accept': 'application/json'},
});`

**Comment by markospy** [comment]
> ```tsx
> export type Res = Record<string, any>
> 
> export type Error = {
>     status: number,
>     msg: string
> }
> 
> export const fetchData = (token: string, date:  DateIn): Promise<Res | Error> => {
>     const res: TRes | undefined = undefined
>     try {
>         const data = axi.get('/statistics/monthly-summary', {
>             params: { year: date.year, month: date.month},
>             headers: {'Authorization': `Bearer ${token}`}
>         })
>         res = data.data
>     } catch(error){
>        res = { status: errorr.response.status, msg: error.message }
>     }
>     return res
> }
> ```

Segui tus sugerencias pero adapatandolas a then/catch. 

```
type UserOut = {
    name: string;
    email: string;
    id: number;
}

export interface ErrorResponse {
    status: number;
    msg: string;
}

export const createUser = (user: UserIn): Promise<UserOut | ErrorResponse > => {
    return axi.post('/user', user)
        .then(response => response.data)
        .catch((error: AxiosError) => {
            // Asegúrate de que error.response esté definido
            const status = error.response?.status || 500; // Valor por defecto
            const msg = error.message;

            return {
                status,
                msg
            };
        });
};
```

**Comment by alnavarrop99** [comment]
Todos estan correctos, tienes razon vite es diferente, importante solo en este aspecto manten el prefijo **`VITE_`** o el que le hayas configurado en la configuracion del mismo para que vite por inyecte correctamente el valor. Por lo demas si esta correcto saludos.
